version: '3'
services:
  web:
    image: "petfinder-updator:latest"
    ports:
      - "8080:8080"
    environment:
      - PETFINDER_API_KEY=$PETFINDER_API_KEY
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=petfinder
  postgres:
    image: "postgres:9.6.2"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=petfinder
    volumes:
      - "../postgres:/docker-entrypoint-initdb.d/"
