apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-rewrite-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: www.austin-ouyang.com
      http:
        paths:
        - path: /grafana/
          backend:
            serviceName: grafana
            servicePort: 80
